version: "2"

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yml

nav:
  - index.md
  - Administration:
    - ./administration/introduction.md
    - "./administration/*"
  - CHPC:
      - "./chpc/*"
  - Analysis Tools:
      - "./analysis_tools/*"
  - Tutorials:
      - "./tutorials/*"


python:
   install:
   - requirements: docs/requirements.txt

formats:
  - pdf
  - epub
