site_name: Clark Group Knowledge Base
theme:
  name: readthedocs
  highlightjs: true
  features:
    - navigation.indexes

nav:
  - index.md
  - Administration:
    - ./administration/introduction.md
    - "./administration/*"
  - CHPC:
      - "./chpc/*"
  - Analysis Tools:
      - "./analysis_tools/*"
  - Tutorials:
      - "./tutorials/*"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
