site_name: Clark Group Knowledge Base
theme:
  name: readthedocs
  highlightjs: true

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.indexes

nav:
  - Home: index.md
  - Administration:
    - Introduction: ./administration/introduction.md
    - Group Requirements: ./administration/group_requirements.md
    - Getting Setup at Utah: ./administration/setup.md
  - CHPC:
      - Arbiter: ./chpc/arbiter.md
      - SLURM: ./chpc/slurm.md
  - Analysis Tools:
      - ChemNetworks: ./analysis_tools/chemnetworks.md
      - GMX Tools: ./analysis_tools/gmx_tools.md
      - VMD: ./analysis_tools/vmd.md
      - OVITO: ./analysis_tools/ovito.md
  - Tutorials:
      - Umbrella Sampling: ./tutorials/umbrella_sampling.md
      - Viscosity Calculation: ./tutorials/visocisty_calculation.md
      - Diffusion Coefficient: ./tutorials/diffusion_coefficient.md
      - Lifetime Analysis: ./tutorials/lifetime_analysis.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .