site_name: Clark Group Knowledge Base
theme:
  name: readthedocs
  highlightjs: true
  features:
    - navigation.indexes

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
