site_name: Basic MkDocs Example Project
theme:
  name: readthedocs
  highlightjs: true

nav:
  - About: index.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: ./administration