site_name: Clark Group Knowledge Base
theme:
  name: readthedocs
  highlightjs: true
  features:
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.indexes
    - navigation.tabs
    - navigation.top

strict: true
nav:
  - About: index.md
  - CHPC:
      - chpc/arbiter.md
  - Tutorials:
      - tutorials/diffusion_coefficient.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
