site_name: Clark Group Knowledge Base
theme:
  name: readthedocs
  highlightjs: true

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.indexes


plugins:
  - search
  - mkdocs-video
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .